version: "3.9"

services:
  gtzan_api:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      UVICORN_WORKERS: 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 5
